name: Constable Deploy

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry and Dependencies
        run: |
          pip install --upgrade poetry==1.3.1
          poetry config pypi-token.pypi $PYPI_IAM_ACTIONS_TOKEN
          poetry install --with dev
        shell: bash
        env:
          PYPI_IAM_ACTIONS_TOKEN: ${{ secrets.PYPI_IAM_ACTIONS_TOKEN }}

      - name: Run Scrape
        run: |
          poetry run python -m iam_actions.generate.generate
          poetry run python -m iam_actions.generate.notifier  

      - name: Create Version Number
        id: version_number
        run: |
          export VERSION=$(grep version pyproject.toml | grep -Po "(\d+\.)" | tr -d '\n')
          export NEW_VERSION=$VERSION$(date +%Y%m%d)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Correct version
        run: |
          sed -i "/^version =.*/c\version = \"${{ env.NEW_VERSION }}\"" pyproject.toml

      - name: Publish
        run: poetry publish --build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iam_action_json
          path: |
            iam_actions/*.json

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: ${{ env.NEW_VERSION }}